config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "posts#index"
  get 'posts' => 'posts#index'
  get "posts/today" => "posts#today"
  get "posts/ranking" => "posts#ranking"
  # get "posts/indexusername" => "posts#indexusername"
  get "users/likes/:id" => "users#likes"
  resources :users, only: [:show]
  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :answers
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :answers, dependent: :destroy
    belongs_to :user
    has_many :liked_users, through: :likes, source: :user # liked_usersによって投稿が誰にいいねされているのかを簡単に取得できるようになります。
    def already_liked?(post)
        self.likes.exists?(post_id: post.id)
    end
    def self.create_all_ranks # ランキング機能のための記述！
        Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:today,:ranking,:show,:edit,:create,:update,:destroy,:indexusername]

  # GET /posts
  # GET /posts.json
  def index
    if params[:search] == nil
      @posts = Post.all.page(params[:page]).per(6)
    elsif params[:search] == '' 
      @posts = Post.all.page(params[:page]).per(6)
    else
      @posts = Post.where("body LIKE ? OR username LIKE ?", '%' + params[:search] + '%','%' + params[:search] + '%').page(params[:page]).per(6)
    end
    #@current_user=current_user.id
    #@ai = Post.find(params[:id])
    # @like = Like.new
    #m @post = Post.find(params[:id])
    # @post = Post.find(params[:id])
  end


  def today
    @posts = Post.order("RANDOM()").limit(1)
  end

  def ranking
    @all_ranks = Post.create_all_ranks
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
      @post = Post.find(params[:id])
      @like = Like.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id=current_user.id
    @post.username=current_user.name
      if @post.save
        #flash[:notice] = "#{@post.username}さん！<br>新規の問題を投稿しましたよ！"
        flash[:notice] = "問題を投稿しました"
        redirect_to :root
      else
        render action: :new
      end
  end


  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if flash[:notice] %>
  <p class="flash post-new-post"><i class="far fa-paper-plane"></i><%= flash[:notice].html_safe %></p>
<% end %>

<h1 class="index-title">ウミガメのスープ問題集</h1>
<div class="search-area">
  <%= form_tag({controller:"posts",action:"index"}, method: :get,class: "search-form") do %>
    <%= text_field_tag :search,'' ,placeholder: "気になる単語を入力して検索" %>
    <%= button_tag :type => "submit", :class =>"search-btn" do %>
      <i class="fa fa-search"></i>
    <% end %>
  <% end %>
</div>

<div class="index-questionarea">
  <% @posts.each do |post| %>
    <div class="index-question">
      <p class="proposer">
        <%= link_to(user_path(post.id)) do %>
          <%= post.username %>さんからの投稿
        <% end %>
        <%#= link_to post.username+'さんからの投稿', user_path(post.id) %>
      </p>
      <p class="question-content"><%= post.body %></p>
      <%# ここをshow.html.erbに記述したらいける %>
      <div class="good_answerlink">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(post) %>
          <p><%= link_to(content_tag(:i, '', class: 'fas fa-heart'), post_like_path(id: post.id, post_id: post.id),method: :delete) %><%= post.liked_users.count %></p>
        <% else %>
          <p class="goodbtn"><%= link_to(content_tag(:i, '', class: 'fas fa-heart'), post_likes_path(id: post.id, post_id: post.id),method: :post) %><%= post.liked_users.count %></p>　　<%# <%= link_to 'いいね', post_likes_path(post),method: :post %>
        <% end %>
        <% if post.user_id == current_user.id %>
          <p class="answerlink"><%= link_to '解答作成', new_post_answer_path(post) %></p>
        <% end %>
      <% end %>
      </div>
      <div class="index_icon_area">
        <p><%= link_to(content_tag(:i, '詳細へ', class: 'fas fa-angle-double-right'), post_path(post)) %></p>
        <% if user_signed_in? %> <%# ユーザーがサインインしていれば %>
          <% if post.user_id == current_user.id %>　<%# 投稿のuser_idとログインユーザーのIDが一致していれば %>
            <p><%= link_to(content_tag(:i, '', class: 'far fa-edit'), edit_post_path(post)) %></p>
            <p><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt'), post_path(post), :method => :delete) %></p>
          <% end %>
        <% end %>
        <p><%= link_to(content_tag(:i, '質問', class: 'far fa-comment-dots'), new_post_comment_path(post)) %></p>
      </div>
      <%# ここをshow.html.erbに記述したらいける %>
    </div>
  <% end %>
</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'TOP', posts_path %>

app/views/posts/ranking.html.erb
<h1 class="index-title ranking">良問ランキング</h1>
<div class="index-questionarea">
  <% @all_ranks.each.with_index(1) do |post,i| %>
    <div class="index-question">
      <p class="proposer">第<%= i %>位<br><%= post.username %>さんからの問題</p>
      <p class="question-content"><%= post.body %></p>
      <%# ここをshow.html.erbに記述したらいける %>
      <div class="good_answerlink">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(post) %>
          <p><%= link_to(content_tag(:i, '', class: 'fas fa-heart'), post_like_path(id: post.id, post_id: post.id),method: :delete) %><%= post.liked_users.count %></p>
        <% else %>
          <p class="goodbtn"><%= link_to(content_tag(:i, '', class: 'fas fa-heart'), post_likes_path(id: post.id, post_id: post.id),method: :post) %><%= post.liked_users.count %></p>　　<%# <%= link_to 'いいね', post_likes_path(post),method: :post %>
        <% end %>
        <% if post.user_id == current_user.id %>
          <p class="answerlink"><%= link_to '解答作成', new_post_answer_path(post) %></p>
        <% end %>
      <% end %>
      </div>
      <div class="index_icon_area">
        <p><%= link_to(content_tag(:i, '詳細へ', class: 'fas fa-angle-double-right'), post_path(post)) %></p>
        <% if user_signed_in? %> <%# ユーザーがサインインしていれば %>
          <% if post.user_id == current_user.id %>　<%# 投稿のuser_idとログインユーザーのIDが一致していれば %>
            <p><%= link_to(content_tag(:i, '', class: 'far fa-edit'), edit_post_path(post)) %></p>
            <p><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt'), post_path(post), :method => :delete) %></p>
          <% end %>
        <% end %>
        <p><%= link_to(content_tag(:i, '質問', class: 'far fa-comment-dots'), new_post_comment_path(post)) %></p>
      </div>
      <%# ここをshow.html.erbに記述したらいける %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
  <p id="notice"><%= notice %></p>
  <div class="index-question show">
    <p class="proposer"><%= @post.username %>さんからの問題</p>
    <p class="question-content"><%= @post.body %></p>
  </div>
  <div class="show-content-area">
    <h1 class="show good-count">いいね件数: <%= @post.likes.count %></h1>
    <%#<% if user_signed_in? %>
    <%#  <% if current_user.already_liked?(@post) %>
    <%#    <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
    <%#  <% else %>
    <%#    <%= button_to 'いいね', post_likes_path(@post) %>
    <%#  <% end %>
    <%#<% end %>
    <h1 class="show good-user">いいねしたユーザー</h1>
    <% @post.liked_users.each do |user| %>
      <p class="show good-username"><%= user.name %></p>
    <% end %>

    <%# # 投稿したコメントを表示★★★★★★★★★★★★★★★★★★ %>
    <% @post.comments.each do |comment| %>
      <p class="show comment"><%= comment.answer %><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt show'), post_comment_path(@post,comment), :method => :delete) %></p>
    <% end %>

    <% @post.answers.each do |answer| %>
      <p class="show answer"><%= answer.body %></p>
    <% end %>
    <%# ここまで %>


    <%= link_to '質問する', new_post_comment_path(@post),class: "show to-post-comment" %> |
    <%= link_to 'Edit', edit_post_path(@post),class: "show to-post-edit" %> |
    <%= link_to 'TOP', posts_path,class: "show to-top" %>
  </div>
</div>

app/views/posts/today.html.erb
<% @posts.each do |post| %>
    <h1 class="today-title">今日の一問</h1>
    <div class="index-question today">
      <p class="proposer"><%= post.username %>さんからの問題</p>
      <p class="question-content"><%= post.body %></p>
      <div class="index_icon_area">
        <p><%= link_to(content_tag(:i, '', class: 'fas fa-angle-double-right'), post_path(post)) %></p>
        <p><%= link_to(content_tag(:i, '', class: 'far fa-edit'), edit_post_path(post)) %></p>
        <p><%= link_to(content_tag(:i, '', class: 'far fa-trash-alt'), post_path(post), :method => :delete) %></p>
        <p><%= link_to(content_tag(:i, '質問', class: 'far fa-comment-dots'), new_post_comment_path(post)) %></p>
      </div>
      <%# ここをshow.html.erbに記述したらいける %>
    </div>
<% end %>