config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "posts#index"
  get 'posts' => 'posts#index'
  get "posts/today" => "posts#today"
  get "posts/ranking" => "posts#ranking"
  # get "posts/indexusername" => "posts#indexusername"
  get "users/likes/:id" => "users#likes"
  resources :users, only: [:show]
  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
    resources :answers
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>GoodFunction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%# lightboxのダウンロード %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <%# lightboxのダウンロード %>

    <!-- Remember to include jQuery :) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

    <!-- jQuery Modal -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />

    <%# bootstrap %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%# bootstrap %>
  </head>
  <body>
    <header class="header" id="header">
      <h1><%= link_to "みんガメ",root_path, class: "nav-link" %></h1>
      <div>
        <ul class="header-listarea">
          <% if user_signed_in? %>
            <li>ようこそ！<span class="font-weight-bold"><%= current_user.name %></span>さん</li>
            <li><%= link_to "サインアウト",destroy_user_session_path, class: "nav-link",method: :delete %></li>
            <li><%= link_to "退会する",user_path(current_user.id), class: "nav-link",method: :delete %></li>
          <% else %>
            <li><%= link_to "サインイン",new_user_session_path, class: "nav-link" %></li>
            <li><%= link_to "新規登録",new_user_registration_path, class: "nav-link" %></li>
          <% end %>
          <li><%= link_to 'プロフィール編集', edit_user_registration_path(current_user),class: "nav-link" %></li>
          <li><%= link_to '新規問題の作成', new_post_path,class: "nav-link" %></li>
          <li><%= link_to '今日の一問', posts_today_path,class: "nav-link" %></li>
          <li><%= link_to '良問ランキング', posts_ranking_path,class: "nav-link" %></li>
        </ul>
      </div>
    </header>
    <%#= javascript_pack_tag 'layouts/application' %>
    <div class="contentarea">
      <div class="trigger" id="trigger"></div>
      <%= yield %>
    </div>
  </body>
</html>